# Generated by Django 5.0 on 2024-05-28 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_blog_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='time_of_creation',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
