# Generated by Django 5.0 on 2024-05-28 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_blog_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='comments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=56)),
                ('title', models.CharField(max_length=56)),
                ('category', models.CharField(max_length=56)),
                ('content', models.TextField()),
                ('comment', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.CharField(max_length=56),
        ),
    ]
